# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: cache-dla
      - task: cache-zdb
      - task: main

  cache-dla:
    desc: Abruf der DLA-Daten und Erstellung des lokalen Cache
    cmds:
      - python3 cache_dla.py
    sources:
      - cache_dla.py
      - Taskfile.yml
    generates:
      - cache/cache-dla-zdb.tsv
      - cache/cache-dla-issn.tsv
    preconditions:
      - command -v python3

  cache-zdb:
    desc: Abruf der ZDB-Daten und Erstellung des lokalen Cache
    cmds:
      - python3 cache_zdb.py
    sources:
      - input/ezb-dla-kbart.tsv
      - cache_zdb.py
      - Taskfile.yml
    generates:
      - cache/cache-zdb.tsv
    preconditions:
      - command -v python3

  transform:
    desc: Transformation EZB-Daten in DLA-OPAC-Internformat
    cmds:
      - python3 ezb_dla_opac.py --input input/ezb-dla-kbart.tsv --zdb-cache cache/cache-zdb.tsv --output output/ezb.tsv
    sources:
      - input/ezb-dla-kbart.tsv
      - cache/cache-zdb.tsv
      - ezb_dla_opac.py
      - Taskfile.yml
    generates:
      - output/ezb.tsv
    preconditions:
      - command -v python3
